package com.example.francis.examinationsystem.model.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.francis.examinationsystem.entity.User;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER".
*/
public class UserDao extends AbstractDao<User, String> {

    public static final String TABLENAME = "USER";

    /**
     * Properties of entity User.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property UserAccount = new Property(0, String.class, "userAccount", true, "USER_ACCOUNT");
        public final static Property UserPsw = new Property(1, String.class, "userPsw", false, "USER_PSW");
        public final static Property UserName = new Property(2, String.class, "userName", false, "USER_NAME");
        public final static Property UserHead = new Property(3, String.class, "userHead", false, "USER_HEAD");
        public final static Property UserEmail = new Property(4, String.class, "userEmail", false, "USER_EMAIL");
        public final static Property School = new Property(5, String.class, "school", false, "SCHOOL");
    }


    public UserDao(DaoConfig config) {
        super(config);
    }
    
    public UserDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER\" (" + //
                "\"USER_ACCOUNT\" TEXT PRIMARY KEY NOT NULL ," + // 0: userAccount
                "\"USER_PSW\" TEXT," + // 1: userPsw
                "\"USER_NAME\" TEXT," + // 2: userName
                "\"USER_HEAD\" TEXT," + // 3: userHead
                "\"USER_EMAIL\" TEXT," + // 4: userEmail
                "\"SCHOOL\" TEXT);"); // 5: school
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, User entity) {
        stmt.clearBindings();
 
        String userAccount = entity.getUserAccount();
        if (userAccount != null) {
            stmt.bindString(1, userAccount);
        }
 
        String userPsw = entity.getUserPsw();
        if (userPsw != null) {
            stmt.bindString(2, userPsw);
        }
 
        String userName = entity.getUserName();
        if (userName != null) {
            stmt.bindString(3, userName);
        }
 
        String userHead = entity.getUserHead();
        if (userHead != null) {
            stmt.bindString(4, userHead);
        }
 
        String userEmail = entity.getUserEmail();
        if (userEmail != null) {
            stmt.bindString(5, userEmail);
        }
 
        String school = entity.getSchool();
        if (school != null) {
            stmt.bindString(6, school);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, User entity) {
        stmt.clearBindings();
 
        String userAccount = entity.getUserAccount();
        if (userAccount != null) {
            stmt.bindString(1, userAccount);
        }
 
        String userPsw = entity.getUserPsw();
        if (userPsw != null) {
            stmt.bindString(2, userPsw);
        }
 
        String userName = entity.getUserName();
        if (userName != null) {
            stmt.bindString(3, userName);
        }
 
        String userHead = entity.getUserHead();
        if (userHead != null) {
            stmt.bindString(4, userHead);
        }
 
        String userEmail = entity.getUserEmail();
        if (userEmail != null) {
            stmt.bindString(5, userEmail);
        }
 
        String school = entity.getSchool();
        if (school != null) {
            stmt.bindString(6, school);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public User readEntity(Cursor cursor, int offset) {
        User entity = new User( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // userAccount
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // userPsw
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // userName
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // userHead
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // userEmail
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // school
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, User entity, int offset) {
        entity.setUserAccount(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setUserPsw(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setUserName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setUserHead(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setUserEmail(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setSchool(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final String updateKeyAfterInsert(User entity, long rowId) {
        return entity.getUserAccount();
    }
    
    @Override
    public String getKey(User entity) {
        if(entity != null) {
            return entity.getUserAccount();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(User entity) {
        return entity.getUserAccount() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
